name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          path: markbind
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          path: markbind
      - name: Install Node Modules
        run: cd $GITHUB_WORKSPACE/markbind && npm ci
      - run: cd $GITHUB_WORKSPACE/markbind && pwd && ls -A
#      - run: npm run build --if-present
#      - run: npm test
      - name: Build Docs
        run: cd $GITHUB_WORKSPACE/markbind && node index build docs
#      - name: Archive Docs
#        uses: actions/upload-artifact@v1
#        with:
#          name: output
#          path: docs/_site
#      - name: Checkout gh-pages repo
#        run: git clone https://${{ secrets.GH_PAGES_PERSONAL_TOKEN }}@github.com/alyip98/GH-Actions-Test.git gh-pages
#      - uses: actions/checkout@v2
#        with:
#          repository: alyip98/GH-Actions-Test
#          path: gh-pages
#          token: ${{ secrets.GH_TOKEN }}
      - run: git clone https://${{ secrets.GH_TOKEN }}@github.com/alyip98/GH-Actions-Test.git gh-pages
      - run: cd $GITHUB_WORKSPACE/gh-pages && pwd && ls -A
      - run: cp -r markbind/docs/_site gh-pages/${{ github.sha }}
      - run: cd gh-pages && ls && git config user.email "you@example.com" && git config user.name "GH Actions" && git add . && git commit -m "Update built site for ${{ github.sha }}"
      - run: cd gh-pages && git push
