name: Github Pages Preview

on: [pull_request] # Temporarily disable

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Markbind
        uses: actions/checkout@v2
        with:
          path: markbind
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          path: markbind
      - name: Install Node Modules
        run: cd $GITHUB_WORKSPACE/markbind && npm ci
#      - run: npm run build --if-present
#      - run: npm test
      # TODO: Modify baseUrl in site config file
      - name: Build Docs
        run: cd $GITHUB_WORKSPACE/markbind/docs && node ../index build
      - name: Archive Docs
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: markbind/docs/_site
      - name: Clone GH-Pages Repo with Access Token
        run: git clone https://${{ secrets.GH_TOKEN }}@github.com/alyip98/GH-Actions-Test.git gh-pages
      - name: Copy built files
        run: cp -r markbind/docs/_site gh-pages/${{ github.sha }}
      - name: Create commit
        run: cd gh-pages && ls && git config user.email "you@example.com" && git config user.name "GH Actions" && git add . && git commit -m "Update built site for ${{ github.sha }}"
      - name: Push to GH-Pages
        run: cd gh-pages && git push
